### ISSUE TITLE
Android build error

### ISSUE THREAD

**Issue by marcolino** [solinor/react-native-bluetooth-status#11]
On Android, `react-native link react-native-bluetooth-status` seems not to be working (none of the actions indicated in the manual installation are preformed...).

Performing manual installation, when compiling I get:

```
/home/marco/apps/MyPassGo/node_modules/react-native-bluetooth-status/android/src/main/java/com/solinor/bluetoothstatus/RNBluetoothManagerPackage.java:12: error: RNBluetoothManagerPackage is not abstract and does not override abstract method createJSModules() in ReactPackage
public class RNBluetoothManagerPackage implements ReactPackage {
       ^
1 error
:react-native-bluetooth-status:compileReleaseJavaWithJavac FAILED

```

Any suggestion?

**Comment by eduplus** [comment]
I had published 1.1.3 in the npm, but it wasn't showing here in github. That version should have removed the conflicting overrides that were a breaking change on new versions of RN. Can you update to 1.1.3 and see if it starts working?
