### ISSUE TITLE
react-native 0.55.4 not supported

### ISSUE THREAD

**Issue by pashute** [solinor/react-native-bluetooth-status#17]
I get 

    npm Error!  Missing rep. react@16.0.0-alpha.6, required by react-native-bluetooth-status@1.1.3
    
My react-native info says:

    Environment:
    OS: Windows 10
    Node: 8.11.1
    Yarn: 1.6.0
    npm: 6.0.1
    Watchman: Not Found
    Xcode: N/A
    Android Studio: Version  3.1.0.0 AI-173.4670197

    Packages: (wanted => installed)
    react: 16.3.1 => 16.3.1
    react-native: 0.55.3 => 0.55.3

**Comment by eduplus** [comment]
Dependencies can be updated, if you are in a hurry to get it working, feel free to submit a PR!

**Comment by pashute** [comment]
I did...

**Comment by eduplus** [comment]
Merged.
