### ISSUE TITLE
import BluetoothStatus is failing => doc error 

### ISSUE THREAD

**Issue by croustibat** [solinor/react-native-bluetooth-status#2]
Hi,

instead of 

`import { BluetoothStatus } from 'react-native-bluetooth-status'
`

it should be loaded like this :

`
import { BluetoothManager as BluetoothStatus } from 'react-native-bluetooth-status'
`

Best,

**Comment by eduplus** [comment]
Yeah you are right, doc is updated according to master, but npm hasn't been updated with those changes yet. Thanks for reminding me to do it.

**Comment by eduplus** [comment]
There is now 1.1 published in npm, which should fix this.
