### ISSUE TITLE
iOS warnings

### ISSUE THREAD

**Issue by rares-lupascu** [solinor/react-native-bluetooth-status#22]
anyone encountered these?
![image](https://user-images.githubusercontent.com/3641866/44543834-582a7a80-a719-11e8-89c9-2ff94274b742.png)

**Comment by ahmad2x4** [comment]
I am also getting same warnings. Plus on iOS it does not work.
Did you find a solution for that?

**Comment by eduplus** [comment]
Have you tried 1.3.0. Do you still get these?

**Comment by andonivianez** [comment]
@eduplus , can you tag the different versions of this repo with tags/releases please? 
Thanks a lot!

**Comment by eduplus** [comment]
There is now 1.4.0. Hopefully works now.
