### ISSUE TITLE
Wrong Java import

### ISSUE THREAD

**Issue by MBach** [solinor/react-native-bluetooth-status#3]
In the docs it says:

    import com.solinor.RNBluetoothManagerPackage;

but in fact, it's:

    import com.reactlibrary.RNBluetoothManagerPackage;

**Comment by eduplus** [comment]
There is now 1.1 published in npm, which should fix this.

**Comment by smartdevdom** [comment]
I have same problem with RNBluetoothManagerPackage 

import com.reactlibrary.RNBluetoothManagerPackage;
--

**Comment by eduplus** [comment]
Hmm yeah, it is actually com.solinor.bluetoothstatus.RNBluetoothManagerPackage now, fixing documentation to match.
