### ISSUE TITLE
Release new version?

### ISSUE THREAD

**Issue by staltz** [solinor/react-native-bluetooth-status#34]
[This commit](https://github.com/solinor/react-native-bluetooth-status/commit/37e82c85c13bb6b362e16a94e8b44c634ac76f6c) has been merged into master already, which adds support for React Native >=0.59 but we just need a new version for this library.

As far as I can see, it's just a matter of updating the version field in package.json to `1.4.0` and running `git commit -m'release'`, `git push`, `npm publish`.

**Comment by eduplus** [comment]
Hey finally remembered to do this, sorry for the wait. 1.4.0 is in npm.
