### ISSUE TITLE
Example doesn't work

### ISSUE THREAD

**Issue by jgautheron** [solinor/react-native-bluetooth-status#4]
There are multiple issues with the example:

1. Badly formatted `package.json`
2. The `postinstall` step fails with this error:
```
sed: can't read s/#import <RCTAnimation\/RCTValueAnimatedNode.h>/#import "RCTValueAnimatedNode.h"/: No such file or directory
```

**Comment by eduplus** [comment]
Made some changes to fix these issues, npm has 1.1.1 now, let me know if you still encounter problems.
