### ISSUE TITLE
Delete node_modules in version 1.4.2 via NPM

### ISSUE THREAD

**Issue by mpochron** [solinor/react-native-bluetooth-status#49]
As topic, it says I have duplicated react-native.

**Comment by mpochron** [comment]
https://github.com/solinor/react-native-bluetooth-status/blob/b31e253bae203027d37f5abaf587d4792d2a64c6/package.json#L44

That line should be in devDependcies

**Comment by eduplus** [comment]
I think you are right, there was some problem running jest (CI was red) and there might have been change here. If you are able to change it properly and still run jest tests, please be kind and provide PR and I'll get it merged quickly.

**Comment by mpochron** [comment]
There is already hotfix in PR:

https://github.com/solinor/react-native-bluetooth-status/pull/50
