### ISSUE TITLE
Listening to status change

### ISSUE THREAD

**Issue by i8wu** [solinor/react-native-bluetooth-status#7]
Is it possible to expose a function to listen to the status change instead of having to check every time?

**Comment by eduplus** [comment]
This is actually something I was thinking and already doing. It will be in the next release.

**Comment by i8wu** [comment]
btw if you're looking for inspiration, this fork basically already does it https://github.com/Artirigo/react-native-bluetooth-state

**Comment by rareslupascu** [comment]
any updates on this?
